"""``research/index.md``: the readable list of every idea, which the ideas skill reads first."""

from __future__ import annotations

import json
from pathlib import Path

from .journal import Journal, TrialLedger
from .workspace import Workspace


def _cell(text: object) -> str:
    return str(text).replace("|", "/").replace("\n", " ").strip() or "-"


def _nearest(ws: Workspace, version) -> str:
    path = ws.stage_dir(version.idea, version.slug, version.version, "build") / "result.json"
    if not path.exists():
        return "-"
    nearest = json.loads(path.read_text(encoding="utf-8")).get("nearest") or []
    return ", ".join(f"{n['label']} ({n['correlation'] or 0:.2f})" for n in nearest[:2]) or "-"


def write_index(ws: Workspace) -> Path:
    journal = Journal(ws.journal_path)
    ideas = journal.ideas()
    trials = TrialLedger(ws.trials_path)
    lines = [
        "# Research index",
        "",
        "Generated by `python -m scripts.research status`; do not edit by hand.",
        "",
        (
            f"Configurations evaluated so far: **{trials.count()}** (all count towards the "
            "deflated Sharpe ratio's number of trials)."
        ),
        "",
        "## Ideas",
        "",
        (
            "| Idea | Title | Family | Inputs | Horizon | TF | Source | Versions | Status | "
            "Why it stopped | Nearest fingerprints |"
        ),
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for idea in sorted(ideas.values(), key=lambda state: state.idea):
        latest = idea.latest
        taxonomy = latest.taxonomy
        source = next(
            (
                entry.get("source_id")
                for entry in journal.entries()
                if entry.get("idea") == idea.idea and entry.get("source_id")
            ),
            None,
        )
        row = [
            idea.idea,
            idea.title + (" (pre-journal)" if latest.historical else ""),
            taxonomy.get("family", ""),
            ", ".join(taxonomy.get("inputs") or []),
            taxonomy.get("horizon", ""),
            ", ".join(sorted({v.timeframe for v in idea.versions.values()})),
            source or "-",
            len(idea.versions),
            idea.status,
            latest.failure,
            _nearest(ws, latest),
        ]
        lines.append("| " + " | ".join(_cell(cell) for cell in row) + " |")
    if not ideas:
        lines.append("| - | none yet | | | | | | | | | |")

    screened = trials.frame()
    screened = screened[screened["kind"] == "screen"] if len(screened) else screened
    if len(screened):
        lines += [
            "",
            "## Screened before the journal (not gated)",
            "",
            "Catalogue rules run by `scripts.scan` on the full history. They count as trials and",
            "their fingerprints block new code that re-implements them, but they never passed or",
            "failed a gate, so registering a catalogue rule (or a blend of them) is allowed.",
            "",
            "| Rule | Variants screened |",
            "|---|---|",
        ]
        rules = screened["label"].str.split(" (", n=1, regex=False).str[0]
        for rule, group in screened.groupby(rules):
            variants = sorted({label[len(rule) :].strip(" ()") for label in group["label"]})
            lines.append(f"| {_cell(rule)} | {'; '.join(variants)} |")

    used: dict[str, list[str]] = {}
    for entry in journal.entries():
        if entry["event"] == "idea_registered" and entry.get("source_id"):
            used.setdefault(entry["source_id"], [])
            if entry["idea"] not in used[entry["source_id"]]:
                used[entry["source_id"]].append(entry["idea"])
    lines += ["", "## Sources already used", ""]
    if used:
        lines += [f"- {source}: {', '.join(ids)}" for source, ids in sorted(used.items())]
    else:
        lines.append("- none yet")
    lines.append("")

    ws.index_path.parent.mkdir(parents=True, exist_ok=True)
    ws.index_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return ws.index_path
